const API='http://127.0.0.1:8000/api';let products=[],cart=[];
const fa=n=>Number(n||0).toLocaleString('fa-IR');
async function api(p,o={},retry=true){const headers={'Content-Type':'application/json',...(o.headers||{})};if(typeof accessToken!=='undefined'&&accessToken)headers.Authorization=`Bearer ${accessToken}`;const r=await fetch(API+p,{...o,headers});if(r.status===401&&retry&&typeof refreshAccessToken==='function'&&await refreshAccessToken())return api(p,o,false);if(!r.ok){let detail='خطا در درخواست';try{const x=await r.json();detail=x.detail||detail}catch(_){}throw Error(detail)}return r.json()}
async function refresh(){products=await api('/products');const pos=document.getElementById('posProducts'),manager=document.getElementById('productManager');[pos,manager].forEach((e)=>{if(e){e.innerHTML=products.map(p=>`<button type="button" class="product" data-product="${p.id}"><span class="food">${p.icon||'🍽️'}</span><b>${p.name}</b><p>${p.category}</p><span class="price">${fa(p.price)} تومان</span></button>`).join('');e.querySelectorAll('[data-product]').forEach(b=>b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();add(Number(b.dataset.product))})}});let d=await api('/dashboard'),b=document.querySelectorAll('#dashboard .stat-card b');if(b.length>2){b[0].innerHTML=fa(d.sales)+' <em>تومان</em>';b[1].textContent=fa(d.orders);b[2].textContent=fa(d.customers)}}
function add(id){const productId=Number(id);const p=products.find(x=>Number(x.id)===productId);if(!p){console.error('Emperator POS: product not found',id,products);return alert('محصول انتخاب‌شده پیدا نشد. لطفاً صندوق را بروزرسانی کنید.')}const x=cart.find(x=>Number(x.id)===productId);if(x)x.qty+=1;else cart.push({...p,id:productId,qty:1});renderCart();return true}
function renderCart(){let e=document.getElementById('cart'),t=document.getElementById('total'),s=0;if(!e||!t)return;e.innerHTML=cart.length?cart.map(x=>{s+=Number(x.price)*Number(x.qty);return `<div class="rank"><span>${x.name} × ${x.qty}</span><strong>${fa(Number(x.price)*Number(x.qty))}</strong><button type="button" data-remove="${x.id}">×</button></div>`}).join(''):'سبد سفارش خالی است';t.textContent=fa(s)+' تومان';e.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>Number(x.id)!==Number(b.dataset.remove));renderCart()})}
async function checkout(){if(!cart.length)return alert('ابتدا حداقل یک محصول به سفارش اضافه کنید');try{let o=await api('/orders',{method:'POST',body:JSON.stringify({items:cart.map(x=>({product_id:Number(x.id),quantity:Number(x.qty)})),payment_method:'نقدی'})});cart=[];renderCart();await refresh();alert('سفارش #'+o.id+' با موفقیت ذخیره شد')}catch(e){alert(e.message||'خطا در ثبت سفارش')}}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo(0,0);document.getElementById('moreMenu')?.classList.remove('show')}
let accessToken=null;let refreshToken=localStorage.getItem('emperator_refresh_token');
function authHeaders(extra={}){return accessToken?{...extra,Authorization:`Bearer ${accessToken}`} : extra}
async function saveTokens(data){accessToken=data.access_token;refreshToken=data.refresh_token;localStorage.setItem('emperator_refresh_token',refreshToken)}
async function authRequest(path,options={}){return fetch(API+path,{...options,headers:authHeaders({'Content-Type':'application/json',...(options.headers||{})})})}
async function doLogin(phone,password){const r=await authRequest('/auth/login',{method:'POST',body:JSON.stringify({phone,password})});const d=await r.json();if(!r.ok)throw Error(d.detail||'ورود ناموفق بود');await saveTokens(d);return getMe()}
async function doRegister(name,phone,password,restaurantName){const r=await authRequest('/auth/register',{method:'POST',body:JSON.stringify({name,phone,password,restaurant_name:restaurantName})});const d=await r.json();if(!r.ok)throw Error(d.detail||'ثبت‌نام ناموفق بود');await saveTokens(d);return getMe()}
async function refreshAccessToken(){if(!refreshToken)return false;const r=await fetch(API+'/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});if(!r.ok){accessToken=null;refreshToken=null;localStorage.removeItem('emperator_refresh_token');return false}await saveTokens(await r.json());return true}
async function getMe(){const r=await authRequest('/auth/me');if(!r.ok)throw Error('نشست کاربر معتبر نیست');return r.json()}
async function doLogout(){if(refreshToken&&accessToken)await authRequest('/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:refreshToken})}).catch(()=>{});accessToken=null;refreshToken=null;localStorage.removeItem('emperator_refresh_token');showAuthScreen()}
function setUser(user){const box=document.querySelector('.user');if(box)box.innerHTML=`${(user.name||'ک').slice(0,1)}<span>${user.role||'کاربر'}</span>`}
function showAuthScreen(){document.getElementById('authScreen')?.classList.remove('hidden');document.querySelector('.app-shell')?.classList.add('locked')}
function hideAuthScreen(){document.getElementById('authScreen')?.classList.add('hidden');document.querySelector('.app-shell')?.classList.remove('locked')}
function injectAuthUI(){if(document.getElementById('authScreen'))return;const style=document.createElement('style');style.textContent=`#authScreen{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;background:radial-gradient(circle at top,#25364d,#090e15 70%);padding:20px}.auth-card{width:min(430px,100%);background:#151f2c;border:1px solid #2b3d52;border-radius:18px;padding:28px;box-shadow:0 25px 70px #0009}.auth-brand{text-align:center;margin-bottom:24px}.auth-brand b{display:block;color:#ffcf68;font-size:28px}.auth-brand span{color:#8fa0b3;font-size:12px}.auth-card h2{margin:0 0 18px;text-align:center}.auth-field{display:block;margin:12px 0;color:#8fa0b3;font-size:12px}.auth-field input{display:block;width:100%;margin-top:7px;padding:12px;border-radius:9px;border:1px solid #273648;background:#0d1520;color:#fff;font:inherit;outline:none}.auth-field input:focus{border-color:#e8b84f}.auth-submit{width:100%;margin-top:10px}.auth-switch{width:100%;margin-top:12px;background:transparent;border:0;color:#ffcf68;padding:10px}.auth-error{min-height:20px;color:#ef6675;text-align:center;font-size:12px;margin-top:8px}.hidden{display:none!important}.app-shell.locked{visibility:hidden}`;document.head.appendChild(style);const el=document.createElement('div');el.id='authScreen';el.innerHTML=`<div class="auth-card"><div class="auth-brand"><b>♛ امپراتور</b><span>مدیریت هوشمند کسب‌وکار غذایی</span></div><h2 id="authTitle">ورود به امپراتور</h2><form id="authForm"><input type="hidden" id="authMode" value="login"><label class="auth-field hidden" id="nameField">نام و نام خانوادگی<input name="name" autocomplete="name"></label><label class="auth-field hidden" id="restaurantField">نام رستوران / کسب‌وکار<input name="restaurant_name" autocomplete="organization"></label><label class="auth-field">شماره موبایل<input name="phone" inputmode="tel" autocomplete="tel" required></label><label class="auth-field">رمز عبور<input name="password" type="password" minlength="8" autocomplete="current-password" required></label><div id="authError" class="auth-error"></div><button class="primary auth-submit" id="authSubmit" type="submit">ورود</button><button class="auth-switch" id="authSwitch" type="button">حساب جدید بساز</button></form></div>`;document.body.appendChild(el);const userbar=document.querySelector('.userbar');if(userbar&&!document.getElementById('logoutBtn')){const b=document.createElement('button');b.id='logoutBtn';b.className='iconbtn';b.title='خروج';b.textContent='↪';b.onclick=doLogout;userbar.prepend(b)}}
function setupAuthUI(){const form=document.getElementById('authForm'),mode=document.getElementById('authMode'),restaurant=document.getElementById('restaurantField'),title=document.getElementById('authTitle'),submit=document.getElementById('authSubmit'),switchBtn=document.getElementById('authSwitch'),error=document.getElementById('authError');switchBtn.onclick=()=>{const register=mode.value!=='register';mode.value=register?'register':'login';document.getElementById('nameField').classList.toggle('hidden',!register);restaurant.classList.toggle('hidden',!register);title.textContent=register?'ساخت حساب امپراتور':'ورود به امپراتور';submit.textContent=register?'ساخت حساب و ورود':'ورود';switchBtn.textContent=register?'قبلاً حساب دارم':'حساب جدید بساز';error.textContent=''};form.onsubmit=async event=>{event.preventDefault();error.textContent='';submit.disabled=true;try{const fd=new FormData(form);const user=mode.value==='register'?await doRegister(fd.get('name'),fd.get('phone'),fd.get('password'),fd.get('restaurant_name')):await doLogin(fd.get('phone'),fd.get('password'));setUser(user);hideAuthScreen();await refresh()}catch(e){error.textContent=e.message||'خطایی رخ داد'}finally{submit.disabled=false}}}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
const roleFa=r=>({owner:'مالک',manager:'مدیر',cashier:'صندوقدار',kitchen:'آشپزخانه',accountant:'حسابدار'})[r]||r||'کاربر';let usersCache=[],rolesCache=[];
function injectUsers(){if(document.getElementById('users'))return;const menu=document.getElementById('moreMenu');if(menu){const n=document.createElement('button');n.className='nav';n.dataset.page='users';n.textContent='👤 کاربران و کارکنان';menu.appendChild(n);n.onclick=()=>showPage('users')}const s=document.createElement('section');s.className='page';s.id='users';s.innerHTML=`<div class="page-head"><div><h1>کاربران و کارکنان</h1><p>مدیریت تیم، نقش‌ها و دسترسی‌ها</p></div><button class="primary" id="addUser">＋ افزودن کارمند</button></div><div class="stats mini" id="userStats"></div><div class="panel"><div class="panel-title"><h3>اعضای تیم</h3><button class="textbtn" id="reloadUsers">↻ بروزرسانی</button></div><div class="table" id="userTable"></div></div><div class="panel" style="margin-top:18px"><div class="panel-title"><h3>آخرین فعالیت‌های مدیریتی</h3><button class="textbtn" id="reloadAudit">↻</button></div><div id="auditList">در حال بارگذاری...</div></div>`;document.querySelector('.content').appendChild(s);const st=document.createElement('style');st.textContent=`#users .user-actions{display:flex;gap:6px}#users .user-actions button{border:1px solid #2b3d52;background:#101925;color:#dce5ef;border-radius:8px;padding:7px 9px}.role-badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#26364a;color:#e7c66c;font-size:12px}.status-dot{display:inline-flex;align-items:center;gap:6px}.status-dot:before{content:'';width:8px;height:8px;border-radius:50%;background:#7f8b99}.status-dot.active:before{background:#45c77a}.users-modal{position:fixed;inset:0;z-index:10000;background:#0009;display:grid;place-items:center;padding:20px}.users-modal-card{width:min(520px,100%);background:#151f2c;border:1px solid #2b3d52;border-radius:16px;padding:24px}.users-modal-card label{display:block;color:#9aaabd;font-size:12px;margin:12px 0}.users-modal-card input,.users-modal-card select{width:100%;box-sizing:border-box;margin-top:6px;padding:11px;border-radius:8px;border:1px solid #2b3d52;background:#0d1520;color:#fff}.modal-actions{display:flex;gap:8px;margin-top:18px}.modal-actions button{flex:1}.audit-row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #243244;color:#aab7c6}.audit-row strong{color:#eef3f8}`;document.head.appendChild(st);document.getElementById('addUser').onclick=()=>userModal();document.getElementById('reloadUsers').onclick=loadUsers;document.getElementById('reloadAudit').onclick=loadAudit}
async function loadRoles(){rolesCache=await api('/roles')}
async function loadUsers(){try{await loadRoles();const u=await api('/users');usersCache=u;document.getElementById('userStats').innerHTML=`<div class="stat-card"><div><small>کل کارکنان</small><b>${fa(u.length)}</b></div></div><div class="stat-card"><div><small>فعال</small><b>${fa(u.filter(x=>x.status==='active').length)}</b></div></div><div class="stat-card"><div><small>غیرفعال</small><b>${fa(u.filter(x=>x.status!=='active').length)}</b></div></div>`;document.getElementById('userTable').innerHTML=`<div class="tr th"><span>کاربر</span><span>موبایل</span><span>نقش</span><span>وضعیت</span><span>عملیات</span></div>`+u.map(x=>`<div class="tr"><span><b>${esc(x.name)}</b></span><span>${esc(x.phone)}</span><span><i class="role-badge">${esc(roleFa(x.role))}</i></span><span><i class="status-dot ${x.status==='active'?'active':''}">${x.status==='active'?'فعال':'غیرفعال'}</i></span><span class="user-actions"><button data-e="${x.id}">ویرایش</button><button data-t="${x.id}">${x.status==='active'?'غیرفعال':'فعال'}</button></span></div>`).join('');document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>userModal(+b.dataset.e));document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>toggleUser(+b.dataset.t))}catch(e){document.getElementById('userTable').innerHTML=`<div class="rank">${esc(e.message)}</div>`}}
async function loadAudit(){try{const a=await api('/audit-logs');document.getElementById('auditList').innerHTML=a.slice(0,10).map(x=>`<div class="audit-row"><span><strong>${esc(x.action||'فعالیت')}</strong> ${esc(x.entity_type||'')}</span><small>${esc(x.created_at||'')}</small></div>`).join('')||'فعالیتی ثبت نشده است'}catch(e){document.getElementById('auditList').textContent=e.message}}
function userModal(id){const u=id?usersCache.find(x=>x.id===id):null,m=document.createElement('div');m.className='users-modal';m.innerHTML=`<div class="users-modal-card"><h3>${u?'ویرایش کارمند':'افزودن کارمند'}</h3><form id="uf"><label>نام و نام خانوادگی<input name="name" value="${esc(u?.name||'')}" required></label><label>شماره موبایل<input name="phone" value="${esc(u?.phone||'')}" required></label><label>نقش<select name="role">${rolesCache.map(r=>`<option value="${esc(r.name)}" ${r.name===(u?.role||'cashier')?'selected':''}>${esc(roleFa(r.name))}</option>`).join('')}</select></label>${u?'':'<label>رمز عبور<input name="password" type="password" minlength="8" required></label>'}<div class="modal-actions"><button type="button" id="cancelUser">انصراف</button><button type="submit" class="primary">ذخیره</button></div><div id="ufErr" class="auth-error"></div></form></div>`;document.body.appendChild(m);m.querySelector('#cancelUser').onclick=()=>m.remove();m.querySelector('#uf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),p={name:f.get('name'),phone:f.get('phone'),role:f.get('role')};try{if(u)await api('/users/'+u.id,{method:'PATCH',body:JSON.stringify(p)});else{p.password=f.get('password');await api('/users',{method:'POST',body:JSON.stringify(p)})}m.remove();await loadUsers();await loadAudit()}catch(err){m.querySelector('#ufErr').textContent=err.message}}}
async function toggleUser(id){const u=usersCache.find(x=>x.id===id);if(!u)return;try{await api('/users/'+id,{method:'PATCH',body:JSON.stringify({status:u.status==='active'?'disabled':'active'})});await loadUsers();await loadAudit()}catch(e){alert(e.message)}}
function initUsers(){injectUsers();const baseShow=showPage;window.showPage=function(id){baseShow(id);if(id==='users'){loadUsers();loadAudit()}}}
document.addEventListener('DOMContentLoaded',async()=>{document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));document.getElementById('moreBtn')?.addEventListener('click',()=>document.getElementById('moreMenu').classList.toggle('show'));document.getElementById('checkoutBtn')?.addEventListener('click',checkout);renderCart();injectAuthUI();setupAuthUI();initUsers();showAuthScreen();if(await refreshAccessToken()){try{const user=await getMe();setUser(user);hideAuthScreen();await refresh()}catch(_){showAuthScreen()}}});
