const API='http://127.0.0.1:8000/api';let products=[],cart=[];
const fa=n=>Number(n||0).toLocaleString('fa-IR');
async function api(p,o={},retry=true){const headers={'Content-Type':'application/json',...(o.headers||{})};if(typeof accessToken!=='undefined'&&accessToken)headers.Authorization=`Bearer ${accessToken}`;const r=await fetch(API+p,{...o,headers});if(r.status===401&&retry&&typeof refreshAccessToken==='function'&&await refreshAccessToken())return api(p,o,false);if(!r.ok){let detail='خطا در درخواست';try{const x=await r.json();detail=x.detail||detail}catch(_){}throw Error(detail)}return r.json()}
async function refresh(){products=await api('/products');['products','productManager'].forEach(id=>{let e=document.getElementById(id);if(e){e.innerHTML=products.map(p=>`<button class="product" data-product="${p.id}"><span class="food">${p.icon||'🍽️'}</span><b>${p.name}</b><p>${p.category}</p><span class="price">${fa(p.price)} تومان</span></button>`).join('');e.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>add(+b.dataset.product))}});let d=await api('/dashboard'),b=document.querySelectorAll('#dashboard .stat-card b');if(b.length>2){b[0].innerHTML=fa(d.sales)+' <em>تومان</em>';b[1].textContent=fa(d.orders);b[2].textContent=fa(d.customers)}}
function add(id){let p=products.find(x=>x.id===id),x=cart.find(x=>x.id===id);x?x.qty++:cart.push({...p,qty:1});renderCart()}
function renderCart(){let e=document.getElementById('cart'),t=document.getElementById('total'),s=0;if(!e||!t)return;e.innerHTML=cart.length?cart.map(x=>{s+=x.price*x.qty;return `<div class="rank"><span>${x.name} × ${x.qty}</span><strong>${fa(x.price*x.qty)}</strong><button data-remove="${x.id}">×</button></div>`}).join(''):'سبد سفارش خالی است';t.textContent=fa(s)+' تومان';e.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);renderCart()})}
async function checkout(){if(!cart.length)return alert('ابتدا محصولی اضافه کنید');try{let o=await api('/orders',{method:'POST',body:JSON.stringify({items:cart.map(x=>({product_id:x.id,quantity:x.qty})),payment_method:'نقدی'})});cart=[];renderCart();await refresh();alert('سفارش #'+o.id+' با موفقیت ذخیره شد')}catch(e){alert(e.message||'خطا در ثبت سفارش')}}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo(0,0);document.getElementById('moreMenu')?.classList.remove('show')}

let accessToken=null;let refreshToken=localStorage.getItem('emperator_refresh_token');
function authHeaders(extra={}){return accessToken?{...extra,Authorization:`Bearer ${accessToken}`} : extra}
async function saveTokens(data){accessToken=data.access_token;refreshToken=data.refresh_token;localStorage.setItem('emperator_refresh_token',refreshToken)}
async function authRequest(path,options={}){return fetch(API+path,{...options,headers:authHeaders({'Content-Type':'application/json',...(options.headers||{})})})}
async function doLogin(phone,password){const r=await authRequest('/auth/login',{method:'POST',body:JSON.stringify({phone,password})});const d=await r.json();if(!r.ok)throw Error(d.detail||'ورود ناموفق بود');await saveTokens(d);return getMe()}
async function doRegister(name,phone,password,restaurantName){const r=await authRequest('/auth/register',{method:'POST',body:JSON.stringify({name,phone,password,restaurant_name:restaurantName})});const d=await r.json();if(!r.ok)throw Error(d.detail||'ثبت‌نام ناموفق بود');await saveTokens(d);return getMe()}
async function refreshAccessToken(){if(!refreshToken)return false;const r=await fetch(API+'/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});if(!r.ok){accessToken=null;refreshToken=null;localStorage.removeItem('emperator_refresh_token');return false}await saveTokens(await r.json());return true}
async function getMe(){const r=await authRequest('/auth/me');if(!r.ok)throw Error('نشست کاربر معتبر نیست');return r.json()}
async function doLogout(){if(refreshToken&&accessToken)await authRequest('/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:refreshToken})}).catch(()=>{});accessToken=null;refreshToken=null;localStorage.removeItem('emperator_refresh_token');showAuthScreen()}
function setUser(user){const box=document.querySelector('.user');if(box)box.innerHTML=`${(user.name||'ک').slice(0,1)}<span>${user.role||'کاربر'}</span>`}
function showAuthScreen(){document.getElementById('authScreen')?.classList.remove('hidden');document.querySelector('.app-shell')?.classList.add('locked')}
function hideAuthScreen(){document.getElementById('authScreen')?.classList.add('hidden');document.querySelector('.app-shell')?.classList.remove('locked')}
function injectAuthUI(){if(document.getElementById('authScreen'))return;const style=document.createElement('style');style.textContent=`#authScreen{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;background:radial-gradient(circle at top,#25364d,#090e15 70%);padding:20px}.auth-card{width:min(430px,100%);background:#151f2c;border:1px solid #2b3d52;border-radius:18px;padding:28px;box-shadow:0 25px 70px #0009}.auth-brand{text-align:center;margin-bottom:24px}.auth-brand b{display:block;color:#ffcf68;font-size:28px}.auth-brand span{color:#8fa0b3;font-size:12px}.auth-card h2{margin:0 0 18px;text-align:center}.auth-field{display:block;margin:12px 0;color:#8fa0b3;font-size:12px}.auth-field input{display:block;width:100%;margin-top:7px;padding:12px;border-radius:9px;border:1px solid #273648;background:#0d1520;color:#fff;font:inherit;outline:none}.auth-field input:focus{border-color:#e8b84f}.auth-submit{width:100%;margin-top:10px}.auth-switch{width:100%;margin-top:12px;background:transparent;border:0;color:#ffcf68;padding:10px}.auth-error{min-height:20px;color:#ef6675;text-align:center;font-size:12px;margin-top:8px}.hidden{display:none!important}.app-shell.locked{visibility:hidden}`;document.head.appendChild(style);const el=document.createElement('div');el.id='authScreen';el.innerHTML=`<div class="auth-card"><div class="auth-brand"><b>♛ امپراتور</b><span>مدیریت هوشمند کسب‌وکار غذایی</span></div><h2 id="authTitle">ورود به امپراتور</h2><form id="authForm"><input type="hidden" id="authMode" value="login"><label class="auth-field hidden" id="nameField">نام و نام خانوادگی<input name="name" autocomplete="name"></label><label class="auth-field hidden" id="restaurantField">نام رستوران / کسب‌وکار<input name="restaurant_name" autocomplete="organization"></label><label class="auth-field">شماره موبایل<input name="phone" inputmode="tel" autocomplete="tel" required></label><label class="auth-field">رمز عبور<input name="password" type="password" minlength="8" autocomplete="current-password" required></label><div id="authError" class="auth-error"></div><button class="primary auth-submit" id="authSubmit" type="submit">ورود</button><button class="auth-switch" id="authSwitch" type="button">حساب جدید بساز</button></form></div>`;document.body.appendChild(el);const userbar=document.querySelector('.userbar');if(userbar&&!document.getElementById('logoutBtn')){const b=document.createElement('button');b.id='logoutBtn';b.className='iconbtn';b.title='خروج';b.textContent='↪';b.onclick=doLogout;userbar.prepend(b)}}
function setupAuthUI(){const form=document.getElementById('authForm'),mode=document.getElementById('authMode'),restaurant=document.getElementById('restaurantField'),title=document.getElementById('authTitle'),submit=document.getElementById('authSubmit'),switchBtn=document.getElementById('authSwitch'),error=document.getElementById('authError');switchBtn.onclick=()=>{const register=mode.value!=='register';mode.value=register?'register':'login';document.getElementById('nameField').classList.toggle('hidden',!register);restaurant.classList.toggle('hidden',!register);title.textContent=register?'ساخت حساب امپراتور':'ورود به امپراتور';submit.textContent=register?'ساخت حساب و ورود':'ورود';switchBtn.textContent=register?'قبلاً حساب دارم':'حساب جدید بساز';error.textContent=''};form.onsubmit=async event=>{event.preventDefault();error.textContent='';submit.disabled=true;try{const fd=new FormData(form);const user=mode.value==='register'?await doRegister(fd.get('name'),fd.get('phone'),fd.get('password'),fd.get('restaurant_name')):await doLogin(fd.get('phone'),fd.get('password'));setUser(user);hideAuthScreen();await refresh()}catch(e){error.textContent=e.message||'خطایی رخ داد'}finally{submit.disabled=false}}}

document.addEventListener('DOMContentLoaded',async()=>{document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));document.getElementById('moreBtn')?.addEventListener('click',()=>document.getElementById('moreMenu').classList.toggle('show'));document.getElementById('checkoutBtn')?.addEventListener('click',checkout);renderCart();injectAuthUI();setupAuthUI();showAuthScreen();if(await refreshAccessToken()){try{const user=await getMe();setUser(user);hideAuthScreen();await refresh()}catch(_){showAuthScreen()}}});
