// Emperator universal UI runtime.
(function(){
  const API='http://127.0.0.1:8000/api';
  const nativeFetch=window.fetch.bind(window);
  const getToken=()=>{try{return window.accessToken||null}catch(_){return null}};
  async function request(path,opt={}){let h={'Content-Type':'application/json',...(opt.headers||{})},t=getToken();if(t)h.Authorization='Bearer '+t;let r=await nativeFetch(API+path,{...opt,headers:h});if(r.status===401&&typeof window.refreshAccessToken==='function'){try{if(await window.refreshAccessToken()){h={'Content-Type':'application/json',...(opt.headers||{})};t=getToken();if(t)h.Authorization='Bearer '+t;r=await nativeFetch(API+path,{...opt,headers:h})}}catch(_){}}let text=await r.text(),d=null;try{d=text?JSON.parse(text):null}catch(_){d=text}if(!r.ok)throw Error((d&&d.detail)||'خطا در درخواست');return d}
  if(typeof window.api!=='function')window.api=request;
  function show(id){const el=document.getElementById(id);if(!el)return false;document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));el.classList.add('active');document.querySelectorAll('.nav[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===id));const menu=document.getElementById('moreMenu');if(menu)menu.classList.remove('show');if(id==='inventory'&&window.EmperatorInventory?.load)window.EmperatorInventory.load();if(id==='kitchen'&&window.EmperatorKDS?.load)window.EmperatorKDS.load();if(id==='orders')loadOrders();if(id==='customers')loadCustomers();window.scrollTo(0,0);return true}
  window.showPage=show;window.emperatorNavigate=show;
  async function loadOrders(){try{const data=await request('/orders');const p=document.getElementById('orders'),t=p&&p.querySelector('.table');if(!t)return;t.innerHTML='<div class="tr th"><span>شماره</span><span>مشتری</span><span>مبلغ</span><span>وضعیت</span><span>عملیات</span></div>'+(data||[]).map(o=>`<div class="tr"><span>#${o.id}</span><span>${o.customer_name||'مشتری'}</span><span>${Number(o.total||0).toLocaleString('fa-IR')} تومان</span><b>${o.status||'جدید'}</b><button type="button">مشاهده</button></div>`).join('')||'<div class="empty-panel">سفارشی ثبت نشده است.</div>'}catch(e){}}
  async function loadCustomers(){try{const data=await request('/customers');const p=document.getElementById('customers'),l=p&&p.querySelector('.customer-list');if(!l)return;l.innerHTML=(data||[]).map(c=>`<div class="order"><span>👤 ${c.name||''}</span><span>${c.phone||''}</span><strong>${c.order_count||0} سفارش</strong></div>`).join('')||'<div class="empty-panel">مشتری ثبت نشده است.</div>'}catch(e){}}
  function wire(){
    document.addEventListener('click',function(e){const nav=e.target.closest('.nav[data-page]');if(nav){e.preventDefault();e.stopImmediatePropagation();if(nav.id==='moreBtn'){const m=document.getElementById('moreMenu');if(m)m.style.display='grid';return}show(nav.dataset.page);return}const go=e.target.closest('[data-go]');if(go){e.preventDefault();e.stopImmediatePropagation();show(go.dataset.go);return}const inv=e.target.closest('[data-inv-action]');if(inv){e.preventDefault();e.stopImmediatePropagation();const a=inv.dataset.invAction;if(!window.EmperatorInventory)return;if(a==='add')window.EmperatorInventory.addItem?.();else if(a==='entry')window.EmperatorInventory.tab?.('movement','adjustment_in');else if(a==='exit')window.EmperatorInventory.tab?.('movement','adjustment_out');else if(a==='waste')window.EmperatorInventory.tab?.('movement','waste');}},true);
    const more=document.getElementById('moreBtn');if(more)more.style.display='block';
    const menu=document.getElementById('moreMenu');if(menu){menu.style.display='none';menu.style.position='fixed';menu.style.top='86px';menu.style.right='20px';menu.style.zIndex='1000';menu.style.background='var(--panel)';menu.style.border='1px solid var(--line)';menu.style.padding='8px';menu.style.borderRadius='12px';menu.style.gridTemplateColumns='1fr';menu.style.gap='4px'}
    const first=document.querySelector('.page.active')||document.querySelector('.page');if(first&&!document.querySelector('.page.active'))show(first.id);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();
