import React, { useMemo, useState } from 'react';

const sample = [
 {id:'#1048',customer:'مریم احمدی',phone:'0912•••۴۲۱',items:'۲ قلم',total:'۴۸۵٬۰۰۰',time:'۱۲:۴۸',status:'در حال آماده‌سازی'},
 {id:'#1047',customer:'علی رضایی',phone:'۰۹۳۵•••۸۸۱',items:'۴ قلم',total:'۷۲۰٬۰۰۰',time:'۱۲:۳۲',status:'ثبت‌شده'},
 {id:'#1046',customer:'سارا محمدی',phone:'۰۹۱۰•••۲۳۶',items:'۱ قلم',total:'۲۱۰٬۰۰۰',time:'۱۲:۱۵',status:'آماده تحویل'},
 {id:'#1045',customer:'رضا کریمی',phone:'۰۹۱۹•••۶۱۰',items:'۳ قلم',total:'۵۶۰٬۰۰۰',time:'۱۱:۵۸',status:'تحویل‌شده'},
 {id:'#1044',customer:'نگار موسوی',phone:'۰۹۳۰•••۱۷۴',items:'۲ قلم',total:'۳۹۰٬۰۰۰',time:'۱۱:۴۱',status:'لغوشده'}
];
const statuses=['ثبت‌شده','در حال آماده‌سازی','آماده تحویل','تحویل‌شده','لغوشده'];
const statusClass=s=>s==='تحویل‌شده'?'done':s==='لغوشده'?'cancel':s==='آماده تحویل'?'ready':s==='در حال آماده‌سازی'?'making':'new';
export default function Orders(){
 const[q,setQ]=useState(''),[filter,setFilter]=useState('همه'),[showForm,setShowForm]=useState(false),[orders,setOrders]=useState(sample),[customer,setCustomer]=useState(''),[phone,setPhone]=useState(''),[editingId,setEditingId]=useState(null),[notice,setNotice]=useState('');
 const filtered=useMemo(()=>orders.filter(o=>(filter==='همه'||o.status===filter)&&`${o.id} ${o.customer} ${o.phone}`.includes(q.trim())),[orders,q,filter]);
 function addOrder(e){e.preventDefault();const id='#'+(1049+orders.length-sample.length);setOrders(cur=>[{id,customer,phone,items:'—',total:'—',time:'اکنون',status:'ثبت‌شده'},...cur]);setCustomer('');setPhone('');setShowForm(false);setNotice(`سفارش ${id} به فهرست نمونه اضافه شد.`)}
 function changeStatus(id,status){setOrders(cur=>cur.map(o=>o.id===id?{...o,status}:o));setEditingId(null);setNotice(`وضعیت سفارش ${id} به «${status}» تغییر کرد.`)}
 return <div className="orders-page"><div className="page-head"><div><span className="eyebrow">مدیریت فروش</span><h1>سفارش‌ها</h1><p>ثبت، پیگیری و مدیریت سفارش‌های مجموعه</p></div><button className="primary" onClick={()=>setShowForm(v=>!v)}>＋ سفارش جدید</button></div>
 {notice&&<div className="form-hint" role="status">{notice} <button className="ghost-btn" onClick={()=>setNotice('')}>×</button></div>}
 <div className="order-summary"><div><small>کل سفارش‌ها</small><b>{orders.length}</b></div><div><small>در جریان</small><b>{orders.filter(o=>['ثبت‌شده','در حال آماده‌سازی','آماده تحویل'].includes(o.status)).length}</b></div><div><small>آماده تحویل</small><b>{orders.filter(o=>o.status==='آماده تحویل').length}</b></div><div><small>تحویل‌شده</small><b>{orders.filter(o=>o.status==='تحویل‌شده').length}</b></div></div>
 {showForm&&<form className="panel order-form" onSubmit={addOrder}><div className="panel-head"><h2>ثبت سفارش سریع</h2><button type="button" className="ghost-btn" onClick={()=>setShowForm(false)}>بستن ×</button></div><div className="form-fields"><label>نام مشتری<input required value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="نام و نام خانوادگی"/></label><label>شماره تماس<input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="09•••••••••" dir="ltr"/></label></div><button className="primary" type="submit">ثبت سفارش</button><small className="form-hint">این نسخه فقط در وضعیت فعلی صفحه داده نگه می‌دارد؛ اتصال API و پایگاه داده هنوز انجام نشده است.</small></form>}
 <section className="panel orders-panel"><div className="orders-tools"><div className="search-box"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جست‌وجوی شماره سفارش، نام یا تلفن..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="فیلتر وضعیت"><option>همه</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="table-wrap"><table className="orders-table"><thead><tr><th>شماره سفارش</th><th>مشتری</th><th>اقلام</th><th>مبلغ کل</th><th>زمان</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td className="order-id">{o.id}</td><td><b>{o.customer}</b><small>{o.phone}</small></td><td>{o.items}</td><td className="amount">{o.total}</td><td>{o.time}</td><td>{editingId===o.id?<select aria-label={`وضعیت سفارش ${o.id}`} value={o.status} onChange={e=>changeStatus(o.id,e.target.value)} onBlur={()=>setEditingId(null)} autoFocus>{statuses.map(s=><option key={s}>{s}</option>)}</select>:<span className={'status-pill '+statusClass(o.status)}>{o.status}</span>}</td><td><button className="row-action" title="تغییر وضعیت سفارش" aria-label={`تغییر وضعیت سفارش ${o.id}`} onClick={()=>setEditingId(editingId===o.id?null:o.id)}>•••</button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="no-results">سفارشی با این مشخصات پیدا نشد.</div>}</div><div className="table-footer"><span>نمایش {filtered.length} سفارش</span><span>صفحه ۱ از ۱</span></div></section></div>
}
